<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>237dfd1f-d721-466b-a818-2ab87b5e202f</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />

    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    <PrivateAssets>all</PrivateAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../TransitPulse.Application/TransitPulse.Application.csproj" />
    <ProjectReference Include="../TransitPulse.Infrastructure/TransitPulse.Infrastructure.csproj" />
  </ItemGroup>

</Project>
